version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: "mysqladmin ping --host=127.0.0.1 --user=root --password=root || exit 1"
      timeout: 5s
      retries: 20
    ports:
      - 3306:3306

  service:
    build:
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db # must be name of mysql container
      MYSQL_USER: root
      MYSQL_PASS: root
      MYSQL_PORT: 3306
      MYSQL_DB: mysql
    ports:
      - 80:80
